"""First Migration

Revision ID: 0b4641263840
Revises: a946ca79f3dd
Create Date: 2022-06-03 14:49:07.560529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4641263840'
down_revision = 'a946ca79f3dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
